ARG CROSS_BASE_IMAGE=scratch
FROM $CROSS_BASE_IMAGE AS base

# cross only exports CROSS_SYSROOT / CROSS_TOOLCHAIN_* into the *run* environment; the
# pinned ghcr.io/cross-rs/x86_64-pc-windows-gnu:0.2.5 image does not bake them in as ENV,
# so at BUILD time they expand to "" and every `$CROSS_SYSROOT/include` below resolves to
# /include -- which is why the header copy died with exit 1. Pin them to what this image
# actually ships (verified: Ubuntu 18.04, gcc 7.3, sysroot /usr/x86_64-w64-mingw32).
# Re-check these if the base image tag is ever bumped.
ENV CROSS_SYSROOT=/usr/x86_64-w64-mingw32
ENV CROSS_TOOLCHAIN_PREFIX=x86_64-w64-mingw32-
ENV CROSS_TOOLCHAIN_SUFFIX=-posix

# -- Overwrite the openssl finder so we just don't do anything (it'll just error out even though we have the lib)
RUN echo "" > $(cmake --system-information | grep CMAKE_ROOT | cut -d'"' -f2)/Modules/FindOpenSSL.cmake

# -- This will enable functionality for cross in the build rs
ENV MOONLIGHT_COMMON_CROSS=1

FROM base AS win

# -- Overwrite system MinGW-w64 headers with latest version
WORKDIR /tmp

# Install wget/unzip if not already present
RUN apt-get update && apt-get install -y wget unzip

# Download latest headers from GitHub
RUN wget -O mingw-w64-headers.zip https://github.com/mirror/mingw-w64/archive/refs/heads/master.zip && \
    unzip mingw-w64-headers.zip

# Copy headers into system MinGW-w64 include folder, overwriting old files
RUN cp -r mingw-w64-master/mingw-w64-headers/include/* $CROSS_SYSROOT/include/ && \
    rm -rf /tmp/*

# -- Some moonlight common c files require windows headers but they have them capitalized so we just symlink them to fix that
RUN ln -s $CROSS_SYSROOT/include/ws2tcpip.h $CROSS_SYSROOT/include/Ws2tcpip.h && \
    ln -s $CROSS_SYSROOT/include/mswsock.h $CROSS_SYSROOT/include/Mswsock.h && \
    ln -s $CROSS_SYSROOT/include/versionhelpers.h $CROSS_SYSROOT/include/VersionHelpers.h && \
    ln -s $CROSS_SYSROOT/include/windows.h $CROSS_SYSROOT/include/Windows.h && \
    ln -s $CROSS_SYSROOT/include/winsock2.h $CROSS_SYSROOT/include/Winsock2.h && \
    # For some reason the stdbool.h is not in the include path
    ln -s /usr/lib/gcc/x86_64-w64-mingw32/$($CROSS_TOOLCHAIN_PREFIX"gcc"$CROSS_TOOLCHAIN_SUFFIX -dumpversion)/include/stdbool.h $CROSS_SYSROOT/include/stdbool.h
